/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GetInTouchRouteImport } from './routes/getInTouch'
import { Route as FooterRouteImport } from './routes/footer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'

const GetInTouchRoute = GetInTouchRouteImport.update({
  id: '/getInTouch',
  path: '/getInTouch',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterRoute = FooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/footer': typeof FooterRoute
  '/getInTouch': typeof GetInTouchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/footer': typeof FooterRoute
  '/getInTouch': typeof GetInTouchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/footer': typeof FooterRoute
  '/getInTouch': typeof GetInTouchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/faq' | '/footer' | '/getInTouch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faq' | '/footer' | '/getInTouch'
  id: '__root__' | '/' | '/faq' | '/footer' | '/getInTouch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  FooterRoute: typeof FooterRoute
  GetInTouchRoute: typeof GetInTouchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/getInTouch': {
      id: '/getInTouch'
      path: '/getInTouch'
      fullPath: '/getInTouch'
      preLoaderRoute: typeof GetInTouchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer': {
      id: '/footer'
      path: '/footer'
      fullPath: '/footer'
      preLoaderRoute: typeof FooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  FooterRoute: FooterRoute,
  GetInTouchRoute: GetInTouchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
